### ISSUE TITLE
unable to find how to use

### ISSUE THREAD

**Issue by matesio** [snowplow/scala-weather#21]
Can you please provide me with some example usage code ,  i am have read all the documentation you provided on github  but i am unable to use it .
Thanks

**Comment by BenFradet** [comment]
You can look at the tests in this project or at [the WeatherEnrichment class](https://github.com/snowplow/snowplow/blob/master/3-enrich/scala-common-enrich/src/main/scala/com.snowplowanalytics.snowplow.enrich/common/enrichments/registry/WeatherEnrichment.scala#L86-L168) for inspiration.

**Comment by chuwy** [comment]
Hi @matesio,

Could you please post your questions to our [forums](http://discourse.snowplowanalytics.com/). Github is for issues only.

Also, if you can provide more details on what you're struggling with - we can provide you more precise answers.

**Comment by matesio** [comment]
sorrry, i was unable to find contact ,

On Tue, Jul 18, 2017 at 3:48 PM, Anton Parkhomenko <notifications@github.com
