### ISSUE TITLE
Add Bintray credentials to .travis.yml

### ISSUE THREAD

**Issue by BenFradet** [snowplow/scala-weather#34]
- `BINTRAY_SNOWPLOW_MAVEN_USER`
- `BINTRAY_SNOWPLOW_MAVEN_API_KEY`

**Comment by BenFradet** [comment]
@alexanderdean 

AFAICT, there is no scala-weather repo in snowplow-maven so that needs to be created too.
Also I think there are some settings to fiddle with in bintray to that the artifacts land in central.

**Comment by alexanderdean** [comment]
Done, https://bintray.com/snowplow/snowplow-maven/scala-weather

Once you push the first rc, ping me and I will do the Maven Central sync

**Comment by alexanderdean** [comment]
By -rc1 I mean -M1!

**Comment by BenFradet** [comment]
it's in bintray, getting:

> failed to sync snowplow/scala-weather@0.3.0-M1 with maven central

as expected

**Comment by alexanderdean** [comment]
Cool, I have clicked the magic button
