### ISSUE TITLE
Bump cats-effect to 1.2.0

### ISSUE THREAD

**Issue by asoltysik** [snowplow/scala-weather#88]
This is required for issue #63

**Comment by dmitraver** [comment]
I can pick this one

**Comment by asoltysik** [comment]
Go ahead! In case you need any help there is a small [contributing guide](https://github.com/snowplow/scala-weather/blob/develop/CONTRIBUTING.md) and a [chat room on gitter](https://gitter.im/snowplow/scala-weather).

**Comment by dmitraver** [comment]
I guess this would come automatically with updated scala-lru-map and hammock

**Comment by BenFradet** [comment]
closing as transient dependency
